### ISSUE TITLE
[TODO]: add actions

### ISSUE THREAD

**Issue by RemcoHalman** [RemcoHalman/small-business-crm#2]
- [x] Stale action
- [x] Python linter

**Comment by RemcoHalman** [comment]
add this to the linter.yml that has to be created

```yaml
name: Linters

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  flake8:
    name: flake8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: python -m pip install flake8
      - name: flake8
        uses: liskin/gh-problem-matcher-wrap@v1
        with:
          linters: flake8
          run: flake8

  isort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: python -m pip install isort
      - name: isort
        uses: liskin/gh-problem-matcher-wrap@v1
        with:
          linters: isort
          run: isort --check --diff django tests scripts
```
